---
- name: Configure projects in AAP Controller and EDA
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infra.aap_configuration

  vars:
    # Provide these via env or -e
    aap_hostname: "{{ lookup('env', 'AAP_HOSTNAME') | default(omit) }}"
    aap_token: "{{ lookup('env', 'AAP_TOKEN') | default(omit) }}"
    aap_validate_certs: "{{ (lookup('env', 'AAP_VALIDATE_CERTS') | default('true')) | bool }}"

    project_name: "llama-stack-rag"
    project_description: "Demo project for Llama Stack RAG"
    project_repo_url: "https://github.com/crenwick93/llama-stack-rag.git"
    project_org: "Default"
    project_branch: "main"

    # Controller project definition
    controller_projects:
      - name: "{{ project_name }}"
        description: "{{ project_description }}"
        organization: "{{ project_org }}"
        scm_type: "git"
        scm_url: "{{ project_repo_url }}"
        scm_branch: "{{ project_branch }}"
        scm_update_on_launch: true

    # EDA project definition
    eda_projects:
      - name: "{{ project_name }}"
        description: "{{ project_description }}"
        organization: "{{ project_org }}"
        scm_type: "git"
        scm_url: "{{ project_repo_url }}"
        scm_branch: "{{ project_branch }}"
        scm_update_on_launch: true

  roles:
    - role: infra.aap_configuration.dispatch
      # Optionally limit to only projects:
      # vars:
      #   aap_configuration_dispatcher_roles:
      #     - controller_projects
      #     - eda_projects


