apiVersion: v1
kind: List
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: k8-diagnostics-agent
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: k8-diagnostics-agent
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: k8-diagnostics-agent:latest
      source:
        type: Binary
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Containerfile
      triggers:
        - type: ConfigChange
        - type: ImageChange


