---
- name: Monitor incidents in ServiceNow
  hosts: all
  execution_strategy: parallel
  sources:
    - servicenow.itsm.records:
        table: incident
        interval: 10
        remote_servicenow_timezone: "Europe/London"
        # newest first to avoid the “oldest page first” trap
        sysparm_query: >
          ORDERBYDESCsys_updated_on^ORDERBYDESCsys_id
      filters:
        - ansible.eda.json_filter:
        - ansible.eda.normalize_keys:
  rules:
    # Debug helper: pretty-print the entire event (toggle by condition)
    # - name: Show event (pretty)
    #   condition: event.meta is defined
    #   action:
    #     print_event:
    #       pretty: true

###############################################################################################
############################ RUN THE DIAGNOSTICS ##############################################

    - name: Run diagnostics and enrich incident
      throttle:
        once_within: 10 minutes
        group_by_attributes:
          - sys_id
      condition: event.short_description is defined
      action:
        run_job_template:
          name: K8s Agent Diagnostics
          organization: Default
          post_events: true
          job_args:
            extra_vars:
              incident_description: "{{ event.short_description + ' ' + event.description }}"
              k8s_agent_base_url: "https://k8-diagnostics-agent-llama-stack-demo.apps.cluster-jqzjt.jqzjt.sandbox1923.opentlc.com"
              incident_sys_id: "{{ event.sys_id }}"


###############################################################################################
#### RULES BELOW WILL BE TRIGGERED ON SECOND RUN (POST_EVENTS:TRUE) IF ANY CONDITIONS MATCH ###

    - name: Raise change if agent diagnostics identifies a resolution for the incident
      condition: >
        event.diagnostics_structured is defined
      action:
        run_workflow_template:
          name: Create Change
          organization: Default
          job_args:
            extra_vars:
              # Change Request fields
              change_short_description: "Emergency change: Nginx issue on {{ event.target_host | default('unknown host') }}"
              change_description: |
                Automated emergency change created by EDA.
                Incident: {{ event.incident_number | default('unknown') }}
                Host: {{ event.target_host | default('unknown host') }}
                Environment: {{ event.environment | default('unknown') }}
                Diagnostics report: {{ event.diagnostics_report | default('') }}

                When the change is approved, the nginx config will be replaced with the last working version.
              change_impact: high
              change_urgency: high
              change_assignment_group: "Event Driven Ansible"
              implementation_job_template_name: "Remediate Nginx Config"
              change_justification: "{{ event.diagnostics_structured.nginx_config_error | default('') }}"

              # Incident fields for the playbook's pre-change incident
              success_update: |
                ########### EDA REMEDIATION STATUS UPDATE - SUCCESS #############
              fail_update: |
                  ########### EDA REMEDIATION STATUS UPDATE - FAIL #############
              work_notes: |
                EDA REMEDIATION STATUS UPDATE - Production incident - Approval Required - Change Request Raised

              # Correlation to link incident and change
              alert_fingerprint: "{{ event.correlation_id | default('') }}"
              # Pass-through context for remediation
              target_host: "{{ event.target_host | default('') }}"
              environment: "{{ event.environment | default('') }}"
              incident_sys_id: "{{ event.sys_id | default('') }}"