---
- name: Monitor incidents in ServiceNow
  hosts: all
  execution_strategy: parallel
  sources:
    - servicenow.itsm.records:
        table: incident
        interval: 10
        remote_servicenow_timezone: "Europe/London"
        # Filter ONLY by assignment group ID; newest first to avoid the “oldest page first” trap
        # sysparm_query: >
        #   assignment_group=9ef342be53a03210a33138f0a0490e85^
        #   ORDERBYDESCsys_updated_on^ORDERBYDESCsys_id
      filters:
        - ansible.eda.json_filter:
        - ansible.eda.normalize_keys:
  rules:
    # Debug helper: pretty-print the entire event (toggle by condition)
    - name: Show event (pretty)
      condition: event.meta is defined
      action:
        print_event:
          pretty: true
